### PR TITLE
Fixing ò and ì

### PR DESCRIPTION
**Pull request by vittoria89**
Just completed the peer review for the Italian translation, just had to fix two accents.
Good job everybody!

### CODE REVIEW

**Comment by Alexintosh** [comment]
Thanks @vittoria89 for the fix.

**Comment by dong77** [comment]
Thank you for the fixes. Are you working with https://github.com/dexlab-io? Otherwise, please send me your NEO and Qtum addresses.

**Comment by vittoria89** [comment]
Hi there! 
you're welcome, I really enjoyed your white paper 
I've been following the dexlab project so that's how I found out about the request for peer review but I'm not directly working with them. 
these are my addresses:

NEO: AeE7ApQpuNDrv8Sd2CKJPMqVzgkYhLoZww
Qtum: QhJYnD6qstJZtbvnLYYzdK8jExBo4rSoiT

Wishing you all the best with the project, 
Vittoria

**Comment by dong77** [comment]
I’ll talk to them regarding how much to pay you, but given that your fixes are minor compared to their original work, I don’t think you’ll get a lot of tokens :)

**Comment by vittoria89** [comment]
Honestly I wasn't expecting any, I'm happy to support both the projects.

**Pull request merged**
